name:  Lambda demo Function

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Choose the region where Lambda is created

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Add any dependencies here

      - name: Deploy Lambda function
        run: |
          zip -r lambda_function.zip .  # Create a zip of your Lambda code
          aws lambda update-function-code \
            --function-name processS3File \
            --zip-file fileb://lambda_function.zip
